version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "48 3 4 * *"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 15
    assignees:
      - "FreDeko06"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      cronjob: "48 3 4 * *"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 15
    assignees:
      - "FreDeko06"
